# Create an OSEv3 group that contains the masters, nodes, and etcd groups
[OSEv3:children]
masters
nodes
etcd

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user=root

# If ansible_ssh_user is not root, ansible_become must be set to true
#ansible_become=true

# deployment type valid values are origin, online, atomic-enterprise, and openshift-enterprise
openshift_deployment_type=openshift-enterprise
oreg_url=example.com/openshift3/ose-${component}:${version}
openshift_examples_modify_imagestreams=true

# uncomment the following to enable htpasswd authentication; defaults to DenyAllPasswordIdentityProvider
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]

openshift_public_hostname=master.ocp.io
openshift_master_default_subdomain=apps.ocp.io

os_sdn_network_plugin_name='redhat/openshift-ovs-multitenant'

#disable disk and memory checks
openshift_disable_check=memory_availability,disk_availability,docker_storage,docker_image_availability

#disable service catalog since it's failing during install
openshift_enable_service_catalog=false
template_service_broker_install=false
ansible_service_broker_install=false

#osm_default_node_selector="region=primary"

# host group for masters
[masters]
master.ocp.io

# host group for etcd
[etcd]
master.ocp.io

# host group for nodes, includes region info
[nodes]
master.ocp.io openshift_node_group_name='node-config-master'
node1.ocp.io openshift_node_group_name='node-config-compute'
node1.ocp.io openshift_node_group_name='node-config-compute'
infra.ocp.io openshift_node_group_name='node-config-infra'
